version: 2

updates:

  - directory: "/"
    package-ecosystem: "npm"
    open-pull-requests-limit: 5
    target-branch: "dev"
    commit-message:
      prefix: "chore(dependencies)"
      include: "scope"
    reviewers:
      - "PedroChaparro"
    schedule:
      timezone: "America/Bogota"
      time: "12:00"
      interval: "daily"