version: "3.8"

services:
  # Databases
  codelabs_postgres_db:
    image: docker.io/library/postgres:alpine3.18
    container_name: codelabs_postgres_db
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: codelabs
    ports:
      - "127.0.0.1:5432:5432"

  # Microservices
  codelabs_static_files:
    image: ghcr.io/upb-code-labs/static-files-microservice:latest
    container_name: codelabs_static_files
    restart: on-failure
    ports:
      - "127.0.0.1:8081:8080"
    depends_on:
      - codelabs_postgres_db

  codelabs_main_api:
    image: ghcr.io/upb-code-labs/main-api:latest
    container_name: codelabs_main_api
    restart: on-failure
    environment:
      - ENVIRONMENT=production
      - DB_CONNECTION_STRING=postgres://postgres:postgres@codelabs_postgres_db:5432/codelabs?sslmode=disable
      - STATIC_FILES_MICROSERVICE_ADDRESS=http://codelabs_static_files:8080
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - codelabs_postgres_db
      - codelabs_static_files

  # Utils
  postgres_db_admin:
    image: docker.io/dpage/pgadmin4:7.6
    container_name: postgres_db_admin
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "127.0.0.1:5050:80"
    depends_on:
      - codelabs_postgres_db
